export const REDUX_STORE_ACTIONS = {
    ACTION_UPDATE_LOADING_GIF: "UPDATE_LOADING_GIF",
    ACTION_UPDATE_RULE_TABLE: "UPDATE_RULE_TABLE",
};

export const REDUX_STORE_MESSAGES = {
    LOADING_GIF_STATUS_MSG: "LOADING_GIF_STATUS",
    INITIAL_RULE_TABLE_MSG: "INITIAL_RULE_TABLE",
    UPDATED_RULE_TABLE_MSG: "UPDATED_RULE_TABLE",
    UPDATED_CODE_RULE_TABLE_MSG: "UPDATED_CODE_RULE_TABLE",
};
